-- Active: 1711142118645@@35.87.147.206@3306@gracious_vampire_625ac0_db
CREATE TABLE IF NOT EXISTS accounts (
    id VARCHAR(255) NOT NULL primary key COMMENT 'primary key', createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Time Created', updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Update', name varchar(255) COMMENT 'User Name', email varchar(255) COMMENT 'User Email', picture varchar(255) COMMENT 'User Picture'
) default charset utf8mb4 COMMENT '';

CREATE TABLE ingredients (
    id INT NOT NULL primary key AUTO_INCREMENT, createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Time Created', updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Update', name VARCHAR(255) NOT NULL, quantity VARCHAR(255) NOT NULL, recipeId INT NOT NULL FOREIGN KEY (recipeId) REFERENCES recipes (id) ON DELETE CASCADE FOREIGN KEY (accountId) REFERENCES accounts (id) ON DELETE CASCADE
)

SELECT * FROM ingredients, recipes

DROP TABLE recipes

CREATE TABLE recipes (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Time Created', updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Update', title VARCHAR(255) NOT NULL, instructions VARCHAR(1000) NOT NULL, img VARCHAR(500) NOT NULL, category ENUM(
        "cheese", "italian", "soup", "mexican", "coffee"
    ), creatorId VARCHAR(255) NOT NULL
)